### ISSUE TITLE
windows 安装服务提示安装成功了但是服务状态没改变，功能不能使用

### ISSUE THREAD

**Issue by 1997CXyYhg** [snail007/proxy_admin_free#15]

**Comment by snail007** [comment]
管理员身份安装

**Comment by gitlsl** [comment]
@snail007 
最新版 用管理员 也是这样
提示按照成功  点确定 又变成服务未运行  点击重启服务  启动后又变成未运行

**Comment by snail007** [comment]
确定你安装的是免费版

**Comment by gitlsl** [comment]
@snail007  当然确定 刚下载的  https://github.com/snail007/proxy_admin_free/releases

**Comment by snail007** [comment]
更新了一下，尝试以下步骤：
1.停止当前服务
2.卸载服务
3.确保c:\gpa文件夹被删除，如果存在，手动删除。
4.重新下载最新版
5.安装
