### ISSUE TITLE
无法连接到文件所在服务器

### ISSUE THREAD

**Issue by ooohawk** [snail007/proxy_admin_free#16]
Resolving mirrors.host900.com (mirrors.host900.com)... 115.238.186.104
Connecting to mirrors.host900.com (mirrors.host900.com)|115.238.186.104|:9090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.

**Comment by ooohawk** [comment]
本地网络无问题

**Comment by snail007** [comment]
已经修复
