### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by peach5460** [snail007/proxy_admin_free#2]
阿里云 windows2012 服务安装正常
启动的时候报错

2019/10/24 10:56:46 Failed to start Proxy Admin Free Edition of (snail007/goprox
y): The service did not respond to the start or control request in a timely fash
ion.

**Comment by snail007** [comment]
需要root权限操作，手动启动看看什么提示，应该是系统限制了什么。

**Comment by peach5460** [comment]
cmd我是管理员启动的，以上报错信息是cmd里面的
在服务窗口里启动，提示“服务没有及时响应启动或控制请求”

**Comment by snail007** [comment]
手动启动,而不是手动启动服务。两者完全不一样。手动启动，直接cmd执行程序。

**Comment by snail007** [comment]
另外，这个错误是系统问题，参考：https://www.cnblogs.com/kerrycode/p/3799239.html

**Comment by peach5460** [comment]
独立启动可以启动，看来是服务的问题，我下午试试链接里的方法

**Comment by peach5460** [comment]
已解决,按第一种方法,设置超时时间就可以了
