### ISSUE TITLE
内网穿透报错，按照教程输入的命令，麻烦看一下

### ISSUE THREAD

**Issue by kamike** [snail007/proxy_admin_free#20]
想通过访问VPS的28000端口访问到公司机器A的8000端口
在centos上面的vps上执行
proxy bridge -p ":33080" -C proxy.crt -K proxy.key --daemon
proxy server -r ":28000@:8000" -P "127.0.0.1:33080" -C proxy.crt -K proxy.key --daemon

proxy [PID] 27211 running...
proxy [PID] 27219 running...
运行成功

在公司机器A(win10系统)上面执行

proxy-admin.exe client -P "vps的ip地址:33080" -C proxy.crt -K proxy.key
报错如下：

>>> goproxy admin free_2.4 <<<

[FATA] 4044: net.Listen error: listen tcp :32080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Stack:
1.  github.com/snail007/proxy-admin/vendor/github.com/gogf/gf/net/ghttp.(*Server).startServer.func1
    /ext-go/6/src/github.com/snail007/proxy-admin/vendor/github.com/gogf/gf/net/ghttp/ghttp_server.go:505

这怎么搞啊

**Comment by snail007** [comment]
这是控制面板，你用命令行goproxy的参数干什么？

**Comment by kamike** [comment]
背景:
公司机器A提供了web服务8000端口
有VPS一个，公网IP:xxxx
需求:
在家里能够通过访问VPS的8000端口访问到公司机器A的8000端口

后续想穿透3389端口，用这个做远程桌面连接公司电脑

**Comment by snail007** [comment]
看视频教程，看手册。
