### ISSUE TITLE
请问下作者，验证码弄成这样真的有意义？？？

### ISSUE THREAD

**Issue by zxiaozhou** [snail007/proxy_admin_free#28]
请问下作者，验证码弄成这样真的有意义？？？何必自己为难自己了
![image](https://user-images.githubusercontent.com/62740686/92389389-943ba700-f14b-11ea-8c40-74404c165495.png)

猫来了也看不清吧！！！！！

**Comment by snail007** [comment]
安全与方便的博弈

**Comment by zxiaozhou** [comment]
好吧，，我没什么说的了，，就是不知道作者这个自己输入要输入几次。。。爽不爽。。。。
