### ISSUE TITLE
启动服务器一天左右占用cpu96%+

### ISSUE THREAD

**Issue by viphxin** [snail007/proxy_admin_free#3]
1) 启动proxy-admin的服务进程
2) 在后台开起一个socks5的代理
3) 在后台开起一个https 代理
4) 正常使用十几个小时左右cpu一直95%+降不下来(代理程序正常使用)
备注：我的服务器是阿里云香港的1核1G的机器，以下为调试日志
[debug.bin.zip](https://github.com/snail007/proxy_admin_free/files/3817643/debug.bin.zip)
![WechatIMG11552](https://user-images.githubusercontent.com/14850723/68355709-0d90f480-014b-11ea-88c1-15b3ffd33d33.jpeg)

**Comment by viphxin** [comment]
这个现象在我这边是毕现的，停过几次服务，cpu又会跑满降不下来

**Comment by snail007** [comment]
分析日志一切正常，时间都花在了socks5大量的建立出口tcp连接上，应该是连接数过多，cpu性能过低，建议增加配置。
