### ISSUE TITLE
nginx代理访问proxyAdmin无法登录

### ISSUE THREAD

**Issue by Architect12138** [snail007/proxy_admin_free#30]
nginx代理访问proxyAdmin登录界面正常，但是无法登录。ip地址访问正常
nginx配置如下，nginx环境（docker部署）
![image](https://user-images.githubusercontent.com/33782068/94355215-e883d800-00b4-11eb-96bf-52fc9b1a9c26.png)
![e764dfc098c31db62e8519d84558fcf](https://user-images.githubusercontent.com/33782068/94355277-76f85980-00b5-11eb-9e2d-d456ed690dbb.png)
登录之后不会跳转到首页，还是登录界面

**Comment by snail007** [comment]
F12看ajax返回什么

**Comment by Architect12138** [comment]
已经解决了，是nginx重定向没有添加端口导致的（302错误），参考网站：https://www.cnblogs.com/sandyyeh/p/10736342.html
