### ISSUE TITLE
内网穿透绑定的地址无法修改，外部访问不了监听端口

### ISSUE THREAD

**Issue by noahzaozao** [snail007/proxy_admin_free#32]
![image](https://user-images.githubusercontent.com/1780032/98892639-b222e080-24db-11eb-80bc-fc47da4e7584.png)

如图，内网穿透无法绑定到正确的网卡，请问可以手动修改吗

**Comment by snail007** [comment]
那是示例，客户端链接你想怎么写怎么写。自己理解错误。
