### ISSUE TITLE
windows版本作为服务运行出现如下报错

### ISSUE THREAD

**Issue by yucendulang** [snail007/proxy_admin_free#34]
Interactive Services Detection服务在新版本的win10已经移除了
请问能否考虑windows版本不去调用这个服务。

报错具体信息如下：

Proxy Admin Free Edition of (snail007/goproxy) 服务标记为交互服务。但是系统配置成不允许交互服务。这项服务可能无法正常操作。

是否还需要提供更详细的报告

**Comment by snail007** [comment]
服务功能是个辅助，不支持更高版本的Windows，不能用服务，就直接命令行运行，用其它工具实现自启动
