### ISSUE TITLE
配置DNS域名后,配置nginx代理访问,登录后的重定向有问题

### ISSUE THREAD

**Issue by SealinGp** [snail007/proxy_admin_free#35]
系统环境
Linux VM-0-17-ubuntu 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
操作步骤:
1.安装proxy_damin
2.配置域名DNS A记录 a.b.c => ip
3.配置linux nginx代理访问
`
server{
   listen 80;
   server_name a.b.c;
   error_log /etc/nginx/logs/goproxy.error.log;

   #frontend

   #gin proxy
   location / {
     proxy_pass http://127.0.0.1:32080/;
   }

   location = /favicon.ico {
     log_not_found off;
   }
}
`
4.访问a.b.c 可以到登录页面,点击登录后重定向到后台失败(页面刷新了,但是还是登录页面)
只能访问a.b.c:32080/ 到登录页面点击登录后重定向到后台成功
盲猜前端路由/后台路由问题,看看作者能不能解决这问题

**Comment by SealinGp** [comment]
另外,作者不考虑选择性的接入个数据库吗..内存占用有点高,把数据都放内存了吗...

**Comment by snail007** [comment]
你这是配置问题，自己翻issues

**Comment by SealinGp** [comment]
更改配置后解决
[http]
listen="127.0.0.1:32080"感谢作者

**Comment by aogg** [comment]
亲怎么解决得啊，我也是代理过来老是登录不进去

**Comment by aogg** [comment]
https://www.cnblogs.com/sandyyeh/p/10736342.html
