### ISSUE TITLE
能否支持树莓派

### ISSUE THREAD

**Issue by jdxia** [snail007/proxy_admin_free#39]
我的是树莓派3B+, 运行报错
>>> downloading ... proxy-admin_linux-amd64.tar.gz

--2021-06-05 11:58:00--  https://mirrors.host900.com/https://github.com/snail007/proxy_admin_free/releases/download/v3.0/proxy-admin_linux-amd64.tar.gz
Resolving mirrors.host900.com (mirrors.host900.com)... 172.67.165.176, 104.21.11.87
Connecting to mirrors.host900.com (mirrors.host900.com)|172.67.165.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16554264 (16M) [application/octet-stream]
Saving to: 'proxy-admin_linux-amd64.tar.gz'

proxy-admin_linux-a 100%[===================>]  15.79M  3.60MB/s    in 5.0s

2021-06-05 11:58:06 (3.14 MB/s) - 'proxy-admin_linux-amd64.tar.gz' saved [16554264/16554264]

>>> installing ...

bash: line 22: ./proxy-admin: cannot execute binary file: Exec format error

**Comment by snail007** [comment]
vip和商业版支持更多平台
