### ISSUE TITLE
unauthorized access

### ISSUE THREAD

**Issue by veo** [snail007/proxy_admin_free#47]
Don't need cookies to access all url，just Location to /login/index

![image](https://user-images.githubusercontent.com/38176360/148884039-cac7106c-34f6-407e-a442-b119f6e7210d.png)

**Comment by snail007** [comment]
invalid, i can not reduce it.

**Comment by veo** [comment]
> invalid, i can not reduce it.

without cookie will jump /login/index,but the operation will still take effect

if go_session_id=a.a,response get 200 and "illegal base64 data at input byte 0"
![image](https://user-images.githubusercontent.com/38176360/148892195-3c4564f4-4ae9-4eb9-a2a4-ef1c918a1233.png)

cookie not work

**Comment by snail007** [comment]
thanks for your feedback , i confirmed this, and fixed in next version, i will publish a new version fixed this soon. but beacuse of securety reason, i closed this issue.

**Comment by veo** [comment]
> thanks for your feedback , i confirmed this, and fixed in next version, i will publish a new version fixed this soon. but beacuse of securety reason, i closed this issue.

ok,and i will delete details
