### ISSUE TITLE
控制面板如何才能支持 https 访问

### ISSUE THREAD

**Issue by qian-jiahong** [snail007/proxy_admin_free#65]
http 可以访问，但是，有其它端口是https，firefox 访问https端口后，再访问控制面板就会自动更改为https，会出错，并提示"SSL 接收到一个超出最大准许长度的记录。"
控制面板如何才能支持 https 访问？

**Comment by michealhansun** [comment]
我只是用来做内网穿透，面板也是不会开启https访问，现在都要用隐身模式才能打开面板，不然都是自动跳转https导致无法打开

**Comment by qian-jiahong** [comment]
已改用 https://github.com/ehang-io/nps
