### ISSUE TITLE
I miss the arm-v8 version

### ISSUE THREAD

**Issue by Mr-joep** [snail007/proxy_admin_free#75]
Hi I miss the arm-v8 version
the proxy does have a v8
(https://github.com/snail007/goproxy/releases/download/v14.0/proxy-linux-arm-v8.tar.gz)

Is there anything known yet when a V8 will be released?
or how could I make it my self?

Thank you in advance and for the effort you have taken!

**Comment by snail007** [comment]
no this pair arm-v8.
