### ISSUE TITLE
请问eth0网卡同时有ipv4和ipv6地址时，出口IP同时支持这两种IP吗？

### ISSUE THREAD

**Issue by gooboy1018** [snail007/proxy_admin_free#81]
vps有v4和v6地址，想的通过ipv4作为入口IP，出口IP为v6地址来访问IPV6服务，场景是公司只有V4地址，家宽ipv6公网地址，想的通过vps来中转一下。
看了手册貌似通过下面参数来支持：proxy socks -t tcp -p :58900 --bind-ip eth0:58900
但试了下这里面--bind-ip参数提示为商业版功能，请问通过上面参数命令确实能解决上面的问题吗？

**Comment by snail007** [comment]
商业版可以试用，自测一下吧
